version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - binary: "ficsit-exporter"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
